"""empty message

Revision ID: 03452653ce82
Revises: 4ac296cbe120
Create Date: 2023-03-12 21:19:57.357543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03452653ce82'
down_revision = '4ac296cbe120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('bathrooms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('bathrooms',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
