"""empty message

Revision ID: 4ac296cbe120
Revises: 2dd1150e6cce
Create Date: 2023-03-12 17:50:32.452326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac296cbe120'
down_revision = '2dd1150e6cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
